export const tags = [
  'Lesbianism',
  'Sexuality',
  'Working class',
  'Black',
  'Asian',
  'Violence against women',
  'Rape',
  'Refuges',
  'Childcare',
  'Housework',
  'Reproductive rights',
  'Demonstrations',
  'Protests',
  'Conferences',
  'Women’s centres',
  'Publishing',
  'Books',
  'Media',
  'Transgender',
  'Tendencies',
  'Conflicts',
  'Irish',
  'Jewish',
  'Education',
  'Work',
  'Health',
  'Music',
  'International',
];

export const locations = [
  'North East',
  'North West',
  'Yorkshire and the Humber',
  'East Midlands',
  'West Midlands',
  'East of England',
  'London',
  'South East',
  'South West',
];

export default { tags, locations };
